AWSTemplateFormatVersion: "2010-09-09"
Description: SAP Data Hub on Amazon EKS new VPC
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - VPCID
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - PublicSubnet3ID
          - RemoteAccessCIDR
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - KeyPairName
      - Label:
          default: EKS configuration
        Parameters:
          - NodeInstanceType
          - NumberOfNodes
          - NodeGroupName
          - NodeVolumeSize
          - AdditionalEKSAdminArns
          - KubernetesVersion
          - ProvisionBastionHost
      - Label:
          default: SAP Data Hub Configuration
        Parameters:
          - SDHInstall
          - SDHVersion
          - SDHSwS3BucketName
          - SDHSwS3PrefixName
          - SDHEcrRepo
          - SDHSUserId
          - SDHSUserPass
          - SDHVoraPass
          - SDHSUserType
          - SDHNameSpace
          - SDHS3AccessKey
          - SDHS3SecretAccessKey
          - SDHCertDomainName
          - SDHELBPrivatePublic
          - NodeInstanceTypeSDH
          - NodeVolumeSizeSDH
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - LambdaZipsBucketName
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      ProvisionBastionHost:
        default: Bastion host
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      NodeInstanceType:
        default: Nodes instance type
      NodeInstanceTypeSDH:
        default: SDH Installation Host instance type
      NumberOfNodes:
        default: Number of nodes
      NodeGroupName:
        default: Node group name
      NodeVolumeSize:
        default: Node volume size
      NodeVolumeSizeSDH:
        default: SDH Installation Host volume size
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PublicSubnet3ID:
        default: Public subnet 3 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      VPCID:
        default: VPC ID
      AdditionalEKSAdminArns:
        default: Additional EKS admin ARNs
      KubernetesVersion:
        default: Kubernetes version
      SDHInstall:
        default: Install the SAP Data Hub?
      SDHVersion:
        default: SAP Data Hub version
      SDHSwS3BucketName:
        default: S3 Bucket name of SAP Data Hub s/w
      SDHSwS3PrefixName:
        default: S3 Prefix name of SAP Data Hub s/w
      SDHEcrRepo:
        default: Create AWS ECR repo for SAP Data Hub
      SDHELBPrivatePublic:
        default: Create Private or Public ELB for SAP Data Hub
      SDHNameSpace:
        default: Kubernetes Name Space for your SAP Data Hub system
      SDHSUserId:
        default: SAP S-User Id.
      SDHSUserPass:
        default: SAP S-User Password
      SDHVoraPass:
        default: SAP Data Hub Vora user's Password
      SDHSUserType:
        default: SAP S-User type (S=S-user, T=Technical-user)
      SDHS3AccessKey:
        default: S3 Access Key
      SDHS3SecretAccessKey:
        default: S3 Secret Access Key
      SDHCertDomainName:
        default: SAP Data Hub Domain Name
Parameters:
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  ProvisionBastionHost:
    Description: Enable or disable the creation of a Bastion host in the first public subnet
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Disabled"
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart-sk
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-sap-datahub-eks/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the instances. We recommend that you set this value to a trusted IP range.
    Type: String
  AdditionalEKSAdminArns:
    Default: ""
    Description: "[OPTIONAL] Comma separated list of IAM user/role ARNs to be granted admin access to the EKS cluster"
    Type: CommaDelimitedList
  NodeInstanceType:
    Default: r4.xlarge
    AllowedValues:
      - t2.2xlarge
      - t3.2xlarge
      - m3.2xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.18xlarge
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - p2.xlarge
      - p2.8xlarge
      - p2.16xlarge
      - p3.2xlarge
      - p3.8xlarge
      - p3.16xlarge
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
      - x1.16xlarge
      - x1.32xlarge
      - x1e.xlarge
      - x1e.2xlarge
      - x1e.4xlarge
      - x1e.8xlarge
      - x1e.16xlarge
      - x1e.32xlarge
      - z1d.xlarge
      - z1d.2xlarge
      - z1d.3xlarge
      - z1d.6xlarge
      - z1d.12xlarge
    ConstraintDescription: Must be a valid EC2 instance type
    Description: Type of EC2 instance for the EKS Worker Node instances
    Type: String
  NumberOfNodes:
    Default: 3
    Description: Number of EKS node instances
    Type: Number
  NodeGroupName:
    Default: my-sap-data-hub-eks-workers
    Description: Name for EKS node group
    Type: String
  NodeVolumeSize:
    Default: 80
    Description: Size for node root EBS volumes
    Type: String
  NodeInstanceTypeSDH:
    Default: r4.xlarge
    AllowedValues:
      - t2.2xlarge
      - t3.2xlarge
      - m4.2xlarge
      - m5.2xlarge
      - i3.xlarge
      - r3.xlarge
      - r4.xlarge
      - r4.2xlarge
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type
    Description: Type of EC2 instance for the SDH Installation Host instance
    Type: String
  NodeVolumeSizeSDH:
    Default: 40
    Description: Size for SDH Installation Host root EBS volumes
    Type: String
  LambdaZipsBucketName:
    Description: 'OPTIONAL: Bucket Name where the lambda zip files should be placed, if left blank a bucket will be created.'
    Type: String
    Default: ''
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: The ID of your existing VPC (e.g., vpc-0343606e)
  PublicSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 1 in your existing VPC (e.g., subnet-a0246dcd)
  PublicSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 2 in your existing VPC (e.g., subnet-b1236eea)
  PublicSubnet3ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the public subnet in Availability Zone 3 in your existing VPC (e.g., subnet-c3456aba)
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 1 in your existing VPC (e.g., subnet-fe9a8b32)
  PrivateSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 2 in your existing VPC (e.g., subnet-be8b01ea)
  PrivateSubnet3ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 3 in your existing VPC (e.g., subnet-abd39039)
  KubernetesVersion:
    Type: String
    AllowedValues: [ "1.11", "1.10" ]
    Default: "1.11"
    Description: Configures the version of kubernetes deployed in the Amazon EKS control plane
  SDHInstall:
    Type: String
    Description: "Do you want to run the SDH installation? Setting to false will provision everthing and get ready for a manual installation."
    AllowedValues: [true, false]
    Default: true
  SDHVersion:
    Type: String
    AllowedValues: [ "2.4", "2.4.1" ]
    Description: Version of SAP Data Hub deployed in the Amazon EKS cluster. **NOTE**, SDH 2.4 is *NOT* compatible with EKS 1.11. See SAP Note "#2686169"
    Default: "2.4.1"
  SDHSwS3BucketName:
    Type: String
    Description: The name of your S3 bucket where your SAP Data Hub software is stored. Do *NOT* include s3:// (use just your bucket name)
    Default: "my-sdh-bucket"
  SDHSwS3PrefixName:
    Type: String
    Description: The name of your S3 key prefix where your SAP Data Hub software is stored.
    Default: my/sw/version/
  SDHEcrRepo:
    Type: String
    Description: "AWS ECR repo to store your SAP Data Hub images. If set to *true*, the repos will be created for you. Set to *false* if you've already created the AWS ECR repos."
    AllowedValues: [true, false]
    Default: true
  SDHELBPrivatePublic:
    Type: String
    Description: "AWS ELB type for your SAP Data Hub Ingress. If set to *PRIVATE*, an ELB is created in your private subnet. If *PUBLIC*, an ELB is created in your public subnet."
    AllowedValues: [PRIVATE, PUBLIC]
    Default: PRIVATE
  SDHNameSpace:
    Type: String
    Description: Your SAP Data Hub kubernetes Name Space
    Default: "datahub"
  SDHSUserId:
    Type: String
    Description: Your SAP SWDC login name
    Default: "S0123456789"
  SDHSUserPass:
    Type: String
    NoEcho: true
    Description: The password for your S-User. This is needed for the SDH Installation only and it not kept after being used.
  SDHVoraPass:
    Type: String
    NoEcho: true
    Description: The password for the Vora user in your SAP Data Hub system.
  SDHSUserType:
    Type: String
    AllowedValues: [ "S", "T" ]
    Description: Type of S-user in the SAP Docker Repository
    Default: "S"
  SDHS3AccessKey:
    Type: String
    NoEcho: true
    Description: The S3 Access Key for your Vora Checkpoint Store.
  SDHS3SecretAccessKey:
    Type: String
    NoEcho: true
    Description: The S3 Secret Access Key for your Vora Checkpoint Store.
  SDHCertDomainName:
    Type: String
    Description: The domain you want to use for your SAP Data Hub system 
    Default: "my-sdh.com"
Rules:
  EKSSupport:
    Assertions: 
      - AssertDescription: Your AWS Region does *NOT* yet support Amazon EKS
        Assert: !Contains 
        -  - us-west-2
           - us-east-1
           - us-east-2
           - eu-west-1
           - eu-west-2
           - eu-west-3
           - eu-north-1
           - eu-central-1
           - ap-southeast-1
           - ap-southeast-2
           - ap-northeast-1
           - ap-northeast-2
           - ap-south-1
        - !Ref 'AWS::Region' 
Resources:
  SDHCheckPointS3Bucket:
    Type: AWS::S3::Bucket
  SDHIAMRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: SDHInstall
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:ListTagsForResource
                  - ecr:TagResource
                  - ecr:DescribeImages
                  - ecr:Batch*
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ec2:Describe*
                  - ec2:DescribeNetworkInterfaces
                  - elasticloadbalancing:Create*
                  - elasticloadbalancing:Describe*
                  - elasticloadbalancing:Delete*
                  - elasticloadbalancing:Register*
                  - elasticloadbalancing:SetIpAddressType
                  - elasticloadbalancing:AddTags
                  - eks:Describe*
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/com.sap*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/elasticsearch*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/fabric8*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/grafana*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kibana*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*kube-state-metrics"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/nginx*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/prom*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/consul*"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/nats-streaming"
              - Effect: Allow
                Action:
                  - ecr:PutImage
                  - ecr:*Delete*
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*vora*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${QSS3BucketName}/*"
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                Resource: !Sub "arn:aws:s3:::${SDHSwS3BucketName}"
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                Resource: !Sub "arn:aws:s3:::${SDHSwS3BucketName}/*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:List*
                Resource: !Sub "arn:aws:s3:::${SDHCheckPointS3Bucket}"
  SDHInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: "SDHIAMRole"
  EKSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SDHInstanceProfile
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks.template.yaml'
      Parameters:
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        PublicSubnet3ID: !Ref PublicSubnet3ID
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub "${QSS3KeyPrefix}submodules/quickstart-amazon-eks/"
        ProvisionBastionHost: !Ref ProvisionBastionHost
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        PrivateSubnet3ID: !Ref PrivateSubnet3ID
        NumberOfNodes: !Ref NumberOfNodes
        NodeGroupName: !Ref NodeGroupName
        NodeVolumeSize: !Ref NodeVolumeSize
        LambdaZipsBucketName: !Ref LambdaZipsBucketName
        NodeInstanceType: !Ref NodeInstanceType
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        AdditionalEKSAdminArns: !GetAtt SDHIAMRole.Arn
        VPCID: !Ref VPCID
        KubernetesVersion: !Ref KubernetesVersion
  SDHStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EKSStack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-sap-data-hub-eks.yaml'
      Parameters:
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        NodeVolumeSizeSDH: !Ref NodeVolumeSizeSDH
        NodeInstanceTypeSDH: !Ref NodeInstanceTypeSDH
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !Ref VPCID
        EKSClusterName: !GetAtt EKSStack.Outputs.EKSClusterName
        KubernetesVersion: !Ref KubernetesVersion
        SDHCheckPointS3Bucket: !Ref SDHCheckPointS3Bucket
        SDHInstall: !Ref SDHInstall
        SDHVersion: !Ref SDHVersion
        SDHSwS3BucketName: !Ref SDHSwS3BucketName
        SDHSwS3PrefixName: !Ref SDHSwS3PrefixName
        SDHEcrRepo: !Ref SDHEcrRepo
        SDHELBPrivatePublic: !Ref SDHELBPrivatePublic
        SDHNameSpace: !Ref SDHNameSpace
        SDHSUserId: !Ref SDHSUserId
        SDHSUserPass: !Ref SDHSUserPass
        SDHVoraPass: !Ref SDHVoraPass
        SDHSUserType: !Ref SDHSUserType
        SDHEnableVoraCheckPoint: !Ref SDHEnableVoraCheckPoint
        SDHS3AccessKey: !Ref SDHS3AccessKey
        SDHS3SecretAccessKey: !Ref SDHS3SecretAccessKey
        SDHCertDomainName: !Ref SDHCertDomainName
        SDHIAMProfile: !Ref SDHInstanceProfile
        SDHIAMRole: !Ref SDHIAMRole
        SDHIAMRoleArn: !GetAtt SDHIAMRole.Arn
Outputs:
  EKSClusterName:
    Value: !GetAtt EKSStack.Outputs.EKSClusterName