global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-sap-datahub-eks
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true
 
tests:
  quickstart-sap-data-hub-ekst1:
    parameter_input: quickstart-sap-datahub-eks.json
    template_file: quickstart-sap-data-hub-on-eks-example1.template
  quickstart-sap-data-hub-on-ekst2:
    parameter_input: quickstart-sap-data-hub-on-eks-example-params2.json
    template_file: quickstart-sap-data-hub-on-eks-example2.template
